### ISSUE TITLE
Can't fully install because `puppeteer` gets stuck installing

### ISSUE THREAD

**Issue by Rudxain** [Le0X8/ChatXtract#3]
Don't worry, this isn't your fault. This happens because `whatsapp-web.js` depends on it.

See this issue: https://github.com/puppeteer/puppeteer/issues/5611

Also related to https://github.com/npm/cli/issues/4028

**Comment by Le0X8** [comment]
That happened to me too, I've stopped the install process and tried it again, and it worked.

**Comment by Rudxain** [comment]
Oh, ok, I'll try more times. I think it's a good idea to put a small note in `README.md` about that
